sudo: required
services: 
    - docker

before_install:
    - docker build -t carljetter/docker-react -f Dockerfile.dev . 

script:
    - docker run carljetter/docker-react npm run test  -- --coverage
